project_id = "iypbievwbwymuuaxnljz"

[functions.google-places]
verify_jwt = false

[functions.geocode]
verify_jwt = false

[functions.gas-prices]
verify_jwt = false

[functions.ticketmaster-events]
verify_jwt = false

[functions.cost-insights]
verify_jwt = false

[functions.media-recommendations]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.create-notification]
verify_jwt = false

[functions.task-reminders]
verify_jwt = false

[functions.contact-form]
verify_jwt = false